# Generated by Django 5.0.6 on 2024-11-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_sale_quantity_alter_sweet_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiwaliWish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('favorite_sweet', models.CharField(max_length=100)),
                ('wish', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Wish',
        ),
    ]
