# Generated by Django 5.0.6 on 2024-11-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_diya_x_coordinate_remove_diya_y_coordinate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participant_count',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='event',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='event',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='type',
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='events', to='myapp.participant'),
        ),
        migrations.AddField(
            model_name='event',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='events', to='myapp.resource'),
        ),
        migrations.AddField(
            model_name='participant',
            name='email',
            field=models.EmailField(default='user@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('Sweet', 'Sweet'), ('Decoration', 'Decoration')], default='Sweet', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
