# Generated by Django 5.0.6 on 2024-11-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_participant_user_alter_participant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sweets/'),
        ),
    ]
