# Generated by Django 5.0.6 on 2024-11-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_event_participants_remove_event_resources_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiwaliCelebration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('special_sweets', models.CharField(max_length=100)),
                ('celebration_description', models.TextField()),
            ],
        ),
    ]
